# Generated by Django 5.0.2 on 2024-04-12 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='employe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
                ('username', models.CharField(max_length=10)),
                ('password', models.CharField(max_length=10)),
                ('qualification', models.CharField(max_length=10)),
                ('skills', models.CharField(max_length=100)),
                ('language', models.CharField(max_length=30)),
                ('experience', models.CharField(max_length=50)),
                ('personal_skills', models.CharField(max_length=60)),
                ('email', models.CharField(max_length=15)),
                ('phone', models.CharField(max_length=10)),
            ],
        ),
    ]
