# Generated by Django 5.0.2 on 2024-04-15 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employe', '0003_details'),
    ]

    operations = [
        migrations.AlterField(
            model_name='details',
            name='email',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='employe',
            name='email',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='employe',
            name='experience',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='employe',
            name='language',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='employe',
            name='personal_skills',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='employe',
            name='qualification',
            field=models.CharField(max_length=60),
        ),
    ]
